# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ibook-ios' do

use_frameworks!
  pod 'Typhoon'
  pod 'ObjectMapper'
  pod 'PromiseKit'
  pod 'SVProgressHUD'
  pod 'googleplus-ios-sdk'
end

target 'ibook-iosTests' do

end

