# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ibook-ios' do

  pod 'AFNetworking', '~> 2.5'
  pod 'Typhoon'

end

target 'ibook-iosTests' do

end

